# 删除用户
# csv文件格式：
# hostname,username
# accuracy,stu1
# ...
---
- name: delete users
  hosts: all          # inventory.yaml中的主机名
  become: 'yes'       # root权限运行
  gather_facts: 'no'  # 不收集主机信息
  vars:
    csv_file: "{{ project_root }}/files/users_2_delete.csv"
  tasks:
    # 读取csv文件
    - name: read users from csv file
      community.general.read_csv:
        path: csv_file
      register: users
    # 检查csv文件内容
    - name: verify csv content
      ansible.builtin.assert:
        that:
          - users is defined
          - users.dict | length > 0
          - users.list | selectattr('username', 'equalto', 'stu0') | length == 0 # 不允许删除stu0
        fail_msg: "Please recheck the 'users_2_delete.csv' file"
    # 删除用户
    - name: delete user
      ansible.builtin.user:
        name: '{{ item.username }}'
        state: absent
      loop: '{{ users.dict }}'
      when: inventory_hostname == item.hostname
    # 归档，防止重复操作
    - name: archive csv file
      ansible.builtin.command:
        cmd: mv "{{csv_file}}" "{{csv_file | dirname}}/.archive/{{ansible_date_time.iso8601_basic_short}}-delete.csv"
      
